version: 0.2

env:

  parameter-store:
    DOCKER_REGISTER_USERNAME: docker-cred
    DOCKER_REGISTRY_PASSWORD: /docker-cred/password
    DOCKER_REGISTRY_URL: docker-url
    
phases:
  install:
    runtime-versions:
      python: 3.11
  pre_build:
     commands:
       - pip install -r day-14/simple-python-app/requirements.txt
  build:
    commands:
      - cd day-14/simple-python-app
      - echo "login docker"
      - echo "$DOCKER_REGISTRY_PASSWORD" | docker login "$DOCKER_REGISTRY_URL" -u "$DOCKER_REGISTER_USERNAME" --password-stdin
      - echo "building docker image"
      - docker build -t "$DOCKER_REGISTRY_URL/$DOCKER_REGISTER_USERNAME/awscodepip:latest" .
      - docker push "$DOCKER_REGISTRY_URL/$DOCKER_REGISTER_USERNAME/awscodepip:latest"
  post_build:
    commands:
      - echo "bild is successful"